name: Leaderboard CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Working in the backend folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate version of Python

      - name: Install backend dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Make sure you have a `requirements.txt`

      # Uncomment and replace with your actual backend test command
      # - name: Run backend tests
      #   run: |
      #     source venv/bin/activate
      #     python -m unittest discover  

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # Working in the frontend folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      # Uncomment and replace with your actual frontend test command
      # - name: Run frontend tests
      #   run: npm test

      - name: Build frontend
        run: npm run build  # Runs `tsc && vite build` to build the project

  deploy:
    name: Deploy App
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy Backend to Render
      - name: Deploy Backend to Render
        run: |
          echo "Deploying backend to Render..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "service_id": "YOUR_BACKEND_SERVICE_ID"
            }' \
            https://api.render.com/v1/services/deploy

      # Deploy Frontend to Render
      - name: Deploy Frontend to Render
        run: |
          echo "Deploying frontend to Render..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "service_id": "YOUR_FRONTEND_SERVICE_ID"
            }' \
            https://api.render.com/v1/services/deploy
