name: Leaderboard CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on push to main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install

      - name: Run backend tests
        run: npm test  # Modify this if you don’t have tests

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test  # Modify this if you don’t have tests

      - name: Build frontend
        run: npm run build  # Only if using a framework like React/Vite

  deploy:
    name: Deploy App
    needs: [backend, frontend]  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: echo "Deploying leaderboard app..."
       

